# Generated by Django 3.1.6 on 2021-02-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Developer', max_length=100, verbose_name='Developer Name')),
                ('designation', models.CharField(default='Developer', max_length=50, verbose_name='Developer Designation')),
                ('description', models.TextField(default='Description not given', verbose_name='Developer Description')),
                ('image', models.ImageField(default='image/White_thumb.png', upload_to='', verbose_name='Developer Name')),
            ],
        ),
        migrations.CreateModel(
            name='ScanTimeTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('H', 'H'), ('I', 'I')], default='1', max_length=1, verbose_name='Timetable Division')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=1, verbose_name='Timetable Semester')),
                ('year', models.CharField(default='2020', max_length=4, verbose_name='Timetable Year')),
                ('image', models.ImageField(default='image/White_thumb.png', upload_to='', verbose_name='Timetable Image')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=10, verbose_name='Short Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='None', max_length=5, verbose_name='Faculty Name')),
                ('batch', models.CharField(choices=[('All', 'All'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='All', max_length=5, verbose_name='Batch Number')),
                ('subject', models.CharField(default='None', max_length=10, verbose_name='Subject Name')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.scantimetablemodel')),
            ],
        ),
    ]
