# Generated by Django 3.1.6 on 2021-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantimetablemodel',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Timetable Year'),
        ),
    ]
