# Generated by Django 3.1.6 on 2021-02-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0002_auto_20210219_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantimetablemodel',
            name='image',
            field=models.ImageField(default='image/White_thumb.png', upload_to='image/', verbose_name='Timetable Image'),
        ),
    ]
